### ISSUE TITLE
Is there support for Asterisk 12 or 13?

### ISSUE THREAD

**Issue by chriscarpenter12** [cdr-stats/cdr-stats#32]
I can't find anywhere saying "yes" it works with asterisk 12 or 13? Seeing as how FreePBX 12 is now stable it supports asterisk 11 and 13 out of the box. Will CDR Stats work with Asterisk 13?

**Comment by areski** [comment]
yes https://github.com/cdr-stats/cdr-pusher should work fine with Asterisk 13
