### ISSUE TITLE
Populate account field from asterisk

### ISSUE THREAD

**Issue by chriscarpenter12** [cdr-stats/cdr-stats#33]
I have two issues:

The account field is not being populated in CDR Stats from my Asterisk/Freepbx server. All calls are imported correctly, but there is not account value. So the customer dashboard doesn't show any data related to their extension.

Also all calls have a direction of unknown vs inbound or outbound. So searching for inbound or outbound calls do not work.

Searched Google Groups, with little results.
![screen shot 2015-01-07 at 10 10 03 am](https://cloud.githubusercontent.com/assets/458486/5647593/665f7e80-9655-11e4-9209-8c8b97e6f9b5.png)

**Comment by chriscarpenter12** [comment]
I have figured out the account field issue. In Freepbx there is a field for "Account Code" on the extension page. I thought this was automatically set based on the phone extension.

Lastly still can't figure out why all calls are unknown vs inbound or outbound.

**Comment by areski** [comment]
If you are using Asterisk, the CDRs doesn't contain direction, other switches like FreeSWITCH give you this information that's why you have it there.

**Comment by chriscarpenter12** [comment]
Can you elaborate on how to get this working with asterisk? I found a few posts in Google Groups relating to this, but nothing descriptive on making it work. My users need to see inbound and outbound numbers.

**Comment by areski** [comment]
by default Asterisk doesnt provide such a feature, you will have to code this yourself in your own CDRs

**Comment by chriscarpenter12** [comment]
Could you update the CDR Stats website to reflect this so people know up front?

**Comment by areski** [comment]
There is many things that need to be updated actually, I will make sure this end up in the FAQ at some stage. It's possible for you to achieve direction in Asterisk CDR you just need to add custom field for it and do some coding changes. I will leave this ticket open util we resolve this, either by FAQ or with proper documentation to teach how to do so on Asterisk.

**Comment by oioki** [comment]
Hello Chris,
To solve similar problem with inbound/outbound identification, I made customization to original CDR-Stats:
https://github.com/oioki/cdr-stats/commit/9264a3d2794cec9f2403e384694925a78df976d8
I am checking length of CallerID number, and if it is equals to 4 (I have 4-digit extensions in my company), then it's likely the outbound call.
Hope that helps.

**Comment by chriscarpenter12** [comment]
@oioki This helps, Thanks. How do you handle internal calls? For instance what is a call to my voicemail box or calling another extension? It's not technically an inbound call or outbound?

**Comment by oioki** [comment]
@chriscarpenter12 I suppose you can achieve this using similar logic:
```
if len(callerid_number) == 4 and len(destination_number) == 4:
    direction = "internal"
```
But I'm not sure if CDR-Stats supports "internal" direction in the frontend.

**Comment by bradsoto** [comment]
@oioki @chriscarpenter12 
I found this thread while searching for a way to tag incoming/outgoing calls using asterisk. We ended up adding some SQL to cdr-pusher.yaml (in cdr_fields):
```
    - orig_field: "CASE WHEN did <> '' THEN 1 ELSE 2 END"
      dest_field: direction
      type_field: int
```
For older version that don't have the DID column we used userfield:
```
    - orig_field: "CASE WHEN userfield <> '' THEN 1 ELSE 2 END"
      dest_field: direction
      type_field: int
```
I thought I'd share our solution.
