### ISSUE TITLE
CentOS 6.6 and centos 6.5 (6.4) cdr-stat start error (for Asterisk)

### ISSUE THREAD

**Issue by alexjd2008** [cdr-stats/cdr-stats#37]
after install il see this error in log /var/log/cdr-stats/err-apache-cdr-stats.log

[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] mod_wsgi (pid=3942): Target WSGI script '/usr/share/cdr_stats/django.wsgi' cannot be loaded as Python module.
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] mod_wsgi (pid=3942): SystemExit exception raised by WSGI script '/usr/share/cdr_stats/django.wsgi' ignored.
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] Traceback (most recent call last):
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]   File "/usr/share/cdr_stats/django.wsgi", line 31, in <module>
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]     import settings
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]   File "/usr/share/cdr_stats/settings.py", line 533, in <module>
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7]     sys.exit(1)
[Thu Feb 12 17:08:36 2015] [error] [client 89.104.118.7] SystemExit: 1

what is it ?

**Comment by alexjd2008** [comment]
It is not work and not many errors in logs. What i doing wrong ?

**Comment by areski** [comment]
Our last vversion work on Debian8, could you try again and reopen the ticket if an issue is still remaining on your side.
