### ISSUE TITLE
Internal calls

### ISSUE THREAD

**Issue by marvin-2016** [cdr-stats/cdr-stats#40]
There is INTERNAL_CALL option in settings.py, but it doesn't seem to do much.
Also, in cdr-stats 2 there was "Internal calls" option in country list, but it is missing in cdr-stats 3.

The calls that I would expect to be internal (shorter than INTERNAL_CALL is set) have the world icon.

**Comment by areski** [comment]
INTERNAL_CALL help one to define the length of phonenumber on their system, see the function `import_cdr` to see where it is used https://github.com/cdr-stats/cdr-stats/blob/develop/cdr_stats/cdr/cdr_importer.py#L115

**Comment by marvin-2016** [comment]
I'm sorry if I'm getting this all wrong. The `import_cdr` function does indeed set the `call_type` to 2, but the code to display the flags here: https://github.com/cdr-stats/cdr-stats/blob/develop/cdr_stats/cdr/templates/cdr/list.html#L208 is just displaying world icon if no `country_id` is set, `call_type` is never checked.
Changing that piece of code to:
```
{% if row.country_id %}
  {% cache 1800 hcountry_flag row.country_id %}
    <img src="{{ STATIC_URL }}cdr-stats/{{ row.country_id|iso_flag }}" class="elemtooltip" title="{{ row.country_id|country_name }}">
   {% endcache %}
{% else %}
  {% if row.call_type == 2 %}
    <img src="{{ STATIC_URL }}cdr-stats/flags/telephone.png" class="elemtooltip" title="{% trans 'internal'|capfirst %}">
  {% else %}
    <img src="{{ STATIC_URL }}cdr-stats/icons/world.png" class="elemtooltip" title="{% trans 'world'|capfirst %}">
{% endif %}
```
Now displays the telephone icon with "internal" tooltip which I expected (because that's how it was handled in older cdr-stats).

**Comment by areski** [comment]
Good call, thanks for the fix ;) https://github.com/cdr-stats/cdr-stats/commit/ad209ec2d340eec0b068032ce686a91d36595576
