### ISSUE TITLE
search return wrong results

### ISSUE THREAD

**Issue by sgalam** [cdr-stats/cdr-stats#41]
Hello,

I installed the 3.1.0. "all is fine". Calls are reported in the analytics page.

Seems that the analytics search function is not working properly, example:

- account code: if i try to search by account code, all records are returned without filtering by my search clause;
- caller id number: if i try to search by caller id number, it return always 0 records;
- cdr per page: every number that I select, I get always 10 records per page;

is it a bug o something related only to this installation?

Thanks

Matteo

**Comment by areski** [comment]
It might be a bug if the rest of the application work properly.

**Comment by sgalam** [comment]
following the guide to enter in the debug mode
http://docs.cdr-stats.org/en/latest/troubleshooting.html
I get this error:

```
(cdr-stats) root@cdrtool:~# workon cdr-stats
(cdr-stats) root@cdrtool:~# cd /usr/share/cdrstats/
(cdr-stats) root@cdrtool:/usr/share/cdrstats# python manage.py celeryd -EB --loglevel=DEBUG
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

```

**Comment by sgalam** [comment]
enabled the debug sidebar uncommenting line
```
# 'debug_toolbar.panels.staticfiles.StaticFilesPanel',
on file /usr/share/cdrstats/cdr_stats/settings.py

```        
entered in debug mode of django under unicorn of your installation:
```
# su - cdr_stats
No directory, logging in with HOME=/
cdr_stats@cdrtool:/$ 
source /opt/miniconda/envs/cdr-stats/bin/activate /opt/miniconda/envs/cdr-stats
cd /usr/share/cdrstats
gunicorn cdr_stats.wsgi:application -b 127.0.0.1:8123 -w 1 --timeout=300

```
I found:

--- **issue** account code: if i try to search by account code, all records are returned without filtering by my search clause;
> resolution: the web ui check that the account code provided in the input box, was already present in the account code related to the user logged in, so you have to create the account code and assign to the right user in order to perform query according this account code. Unless the account code provided in the search field is ignored;

--- **issue** caller id number: if i try to search by caller id number, it return always 0 records;
> **resolution** I found that field caller_id_number on table cdr_voip was empty for all my records. I modified the /etc/cdr-pusher.yaml in order to populate the caler id number:
before:

```
#    - orig_field: "'' AS cidnum"
#      dest_field: caller_id_number
#      type_field: string
after:
    - orig_field: clid
      dest_field: caller_id_number
      type_field: string
```

--- **issue** cdr per page: every number that I select, I get always 10 records per page;
> **resolution** I tried to debug the code but I have not found a solution by now. @areski can you help me in this?

**Comment by areski** [comment]
1) Accountcode
The accountcode filtering work on the cdr view it was solved here https://github.com/cdr-stats/cdr-stats/commit/365c4b9e1182662a2b84c80d5933eef5a5a25a70
You need to create an AccountCode entity and assign it to a user to it to work otherwise simply filtering by the number dont work.

2) callerid:
yes you need to make sure the cid is pushed, that usually depend of your CDR backend

3) cdr per page:
this is a minor known bug, we haven't addressed it yet.

**Comment by sgalam** [comment]
ok thanks. about point 3, where is reported the known minor bug? 
Is it possible to have a issue open on github so when is fixed who is interested know about it?

**Comment by areski** [comment]
Yes, https://github.com/cdr-stats/cdr-stats/issues/42
